# Generated by Django 4.1.7 on 2023-04-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pending'), ('ACEPTADA', 'Accepted'), ('RECHAZADA', 'Rejected')], default='PENDIENTE', max_length=9)),
                ('usr_envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env', to=settings.AUTH_USER_MODEL, verbose_name='user_envia')),
                ('usr_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rec', to=settings.AUTH_USER_MODEL, verbose_name='user_recibe')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
