# Generated by Django 4.1.7 on 2023-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0003_alter_libros_sinopsis_alter_libros_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
