# Generated by Django 4.1.7 on 2023-04-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30, unique=True)),
                ('paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sinopsis', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=9)),
            ],
            options={
                'db_table': 'listas',
            },
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opinion', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.libros')),
            ],
            options={
                'db_table': 'opiniones',
            },
        ),
    ]
